# config/app_config.py

QUERY1 = """SELECT POKE_NAME, HP, ATK, DEF, SPATK, SPDEF, SPD, BST FROM pokemon_main WHERE POKE_NAME LIKE %s"""
QUERY2 = """
    SELECT M.POKE_NAME, M.HP, M.ATK, M.DEF, M.SPATK, M.SPDEF, M.SPD, T.TYPE_1, T.TYPE_2\
    FROM pokemon_main AS M\
    LEFT JOIN pokemon_types AS T\
    ON M.POKE_ID = T.POKE_ID\
    WHERE (M.POKE_ID = %s OR M.POKE_NAME = %s)\
    OR (M.POKE_ID = %s OR M.POKE_NAME = %s)\
    ORDER BY CASE
        WHEN M.POKE_ID = %s OR M.POKE_NAME = %s THEN 1
        WHEN M.POKE_ID = %s OR M.POKE_NAME = %s THEN 2
        ELSE 3
    END
    """
POKEMON_BASE_COLUMNS = ['POKE_NAME', 'HP', 'ATK', 'DEF', 'SPATK', 'SPDEF', 'SPD', 'BST']
POKEMON_BASE_COLUMNS_WITH_TYPES = ['POKE_NAME', 'HP', 'ATK', 'DEF', 'SPATK', 'SPDEF', 'SPD', 'TYPE_1', 'TYPE_2']
POKEMON_EV_COLUMNS = ['HP_EV', 'ATK_EV', 'DEF_EV', 'SPATK_EV', 'SPDEF_EV', 'SPD_EV']
POKEMON_LVL = ['POKE_LVL']
POKEMON_FINAL_STATS_COLUMNS = ['FINAL_HP', 'FINAL_ATK', 'FINAL_DEF', 'FINAL_SPATK', 'FINAL_SPDEF', 'FINAL_SPD']
POKEMON_NAME_LVL = ['POKE_NAME', 'POKE_LVL']